remote_theme: raviriley/agency-jekyll-theme

# For now (GitHub Pages preview)
url    : ""
baseurl: "/olympuslab-site"   # MUST match your repo name exactly

title      : Olympus Lab
email      : trevor.peters@olympuslab.ai
description: "Security, infrastructure, and automation experiments."
author     : Olympus Lab

logo:
  path: assets/img/logo.png
  height: 52

locale: "en-US"
